# Generated by Django 6.0.1 on 2026-01-17 18:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_week1_sunday', models.DateField(verbose_name='بداية الأسبوع الأول (الأحد)')),
                ('weeks_count', models.PositiveSmallIntegerField(default=19, verbose_name='عدد الأسابيع')),
            ],
            options={
                'verbose_name': 'إعدادات الخطة',
                'verbose_name_plural': 'إعدادات الخطة',
            },
        ),
        migrations.CreateModel(
            name='PlanWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='رقم الأسبوع')),
                ('start_sunday', models.DateField(verbose_name='بداية الأسبوع (الأحد)')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='ملاحظة/اسم')),
                ('is_break', models.BooleanField(default=False, verbose_name='إجازة/توقف؟')),
            ],
            options={
                'verbose_name': 'أسبوع خطة',
                'verbose_name_plural': 'أسابيع الخطة',
                'ordering': ['week_no'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_code', models.CharField(max_length=32, unique=True, verbose_name='الرقم الإحصائي')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المدرسة')),
                ('gender', models.CharField(choices=[('boys', 'بنين'), ('girls', 'بنات')], max_length=10, verbose_name='النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'مدرسة',
                'verbose_name_plural': 'المدارس',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='السجل المدني')),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم المشرف')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='جوال المشرف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مشرف',
                'verbose_name_plural': 'المشرفون',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='رقم الأسبوع (قديم)')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمدة'), ('unlock', 'طلب فك اعتماد')], default='draft', max_length=20, verbose_name='الحالة')),
                ('saved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحفظ')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='visits.planweek')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='visits.supervisor')),
            ],
            options={
                'verbose_name': 'خطة أسبوعية',
                'verbose_name_plural': 'الخطط الأسبوعية',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم المدير')),
                ('mobile', models.CharField(max_length=20, verbose_name='الجوال')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='visits.school')),
            ],
            options={
                'verbose_name': 'مدير مدرسة',
                'verbose_name_plural': 'مديرو المدارس',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='visits.school')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='visits.supervisor')),
            ],
            options={
                'verbose_name': 'إسناد مدرسة',
                'verbose_name_plural': 'إسنادات المدارس',
            },
        ),
        migrations.CreateModel(
            name='UnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'معلّق'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_request', to='visits.plan')),
            ],
            options={
                'verbose_name': 'طلب فك اعتماد',
                'verbose_name_plural': 'طلبات فك الاعتماد',
            },
        ),
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'الأحد'), (1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم')),
                ('visit_type', models.CharField(choices=[('in', 'حضوري'), ('remote', 'عن بعد')], default='in', max_length=10, verbose_name='نوع الزيارة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='visits.plan')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='visits.school')),
            ],
            options={
                'verbose_name': 'يوم خطة',
                'verbose_name_plural': 'أيام الخطة',
                'ordering': ['weekday'],
                'unique_together': {('plan', 'weekday')},
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('supervisor', 'week'), name='uniq_plan_supervisor_week'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('supervisor', 'week_no'), name='uniq_plan_supervisor_weekno'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('supervisor', 'school')},
        ),
        migrations.AddConstraint(
            model_name='unlockrequest',
            constraint=models.UniqueConstraint(fields=('plan',), name='uniq_unlock_request_plan'),
        ),
    ]
