# Generated by Django 6.0.1 on 2026-01-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plan',
            name='uniq_plan_supervisor_weekno',
        ),
        migrations.AlterField(
            model_name='plan',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='visits.planweek'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='week_no',
        ),
    ]
