# Generated by Django 6.0.1 on 2026-01-17 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_plan_uniq_plan_supervisor_weekno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanConfig',
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['supervisor__full_name', 'school__name'], 'verbose_name': 'إسناد مدرسة', 'verbose_name_plural': 'إسنادات المدارس'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-id'], 'verbose_name': 'خطة أسبوعية', 'verbose_name_plural': 'الخطط الأسبوعية'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'ordering': ['full_name'], 'verbose_name': 'مدير مدرسة', 'verbose_name_plural': 'مديرو المدارس'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'مدرسة', 'verbose_name_plural': 'المدارس'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['full_name'], 'verbose_name': 'مشرف', 'verbose_name_plural': 'المشرفون'},
        ),
        migrations.AlterModelOptions(
            name='unlockrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب فك اعتماد', 'verbose_name_plural': 'طلبات فك الاعتماد'},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='planday',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='visits.school', verbose_name='المدرسة'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='visits.supervisor', verbose_name='المشرف'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='visits.supervisor', verbose_name='المشرف'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='visits.planweek', verbose_name='الأسبوع'),
        ),
        migrations.AlterField(
            model_name='planday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='visits.plan', verbose_name='الخطة'),
        ),
        migrations.AlterField(
            model_name='planday',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='visits.school', verbose_name='المدرسة'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='visits.school', verbose_name='المدرسة'),
        ),
        migrations.AlterField(
            model_name='unlockrequest',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_request', to='visits.plan', verbose_name='الخطة'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status'], name='visits_plan_status_b30f10_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['week'], name='visits_plan_week_id_8be6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='planday',
            index=models.Index(fields=['weekday'], name='visits_plan_weekday_92b86c_idx'),
        ),
        migrations.AddIndex(
            model_name='planweek',
            index=models.Index(fields=['week_no'], name='visits_plan_week_no_dc11bf_idx'),
        ),
        migrations.AddIndex(
            model_name='planweek',
            index=models.Index(fields=['is_break'], name='visits_plan_is_brea_3b85f7_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['stat_code'], name='visits_scho_stat_co_b0480b_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active'], name='visits_scho_is_acti_ebf025_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['national_id'], name='visits_supe_nationa_55f51c_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['is_active'], name='visits_supe_is_acti_a45f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='unlockrequest',
            index=models.Index(fields=['status'], name='visits_unlo_status_e87516_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('supervisor', 'school'), name='uniq_assignment_sup_school'),
        ),
        migrations.AddConstraint(
            model_name='planday',
            constraint=models.UniqueConstraint(fields=('plan', 'weekday'), name='uniq_planday_plan_weekday'),
        ),
    ]
