# Generated by Django 6.0.1 on 2026-01-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_delete_planconfig_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planday',
            name='no_visit_reason',
            field=models.CharField(blank=True, choices=[('meeting', 'اجتماع'), ('training', 'تدريب'), ('event', 'لقاء/فعالية'), ('office', 'عمل مكتبي'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='سبب عدم الزيارة'),
        ),
        migrations.AddField(
            model_name='planday',
            name='note',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='planday',
            name='visit_type',
            field=models.CharField(choices=[('in', 'حضوري'), ('remote', 'عن بعد'), ('none', 'بدون زيارة مدرسية')], default='in', max_length=10, verbose_name='نوع اليوم'),
        ),
        migrations.AddIndex(
            model_name='planday',
            index=models.Index(fields=['visit_type'], name='visits_plan_visit_t_2a3900_idx'),
        ),
    ]
