# Generated by Django 6.0.1 on 2026-03-11 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_planday_no_visit_reason_planday_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة الإدارة'),
        ),
        migrations.CreateModel(
            name='SupervisorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('approved', 'تم اعتماد الخطة'), ('returned', 'تمت إعادة الخطة للمراجعة'), ('unlock_approved', 'تم قبول طلب فك الاعتماد'), ('unlock_rejected', 'تم رفض طلب فك الاعتماد')], max_length=30, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(blank=True, null=True, verbose_name='نص الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='visits.plan', verbose_name='الخطة')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='visits.supervisor', verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'إشعار مشرف',
                'verbose_name_plural': 'إشعارات المشرفين',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supervisor', 'is_read'], name='visits_supe_supervi_7dc05b_idx'), models.Index(fields=['created_at'], name='visits_supe_created_be838e_idx'), models.Index(fields=['notif_type'], name='visits_supe_notif_t_61f920_idx')],
            },
        ),
    ]
