# Generated by Django 6.0.1 on 2026-03-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_plan_admin_note_supervisornotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الجوال'),
        ),
    ]
