# Generated by Django 6.0.1 on 2026-03-19 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_alter_principal_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLetterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الخطاب')),
                ('drive_url', models.URLField(max_length=1000, verbose_name='رابط الخطاب على Google Drive')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter_link', to='visits.planweek', verbose_name='الأسبوع')),
            ],
            options={
                'verbose_name': 'رابط خطاب أسبوعي',
                'verbose_name_plural': 'روابط الخطابات الأسبوعية',
                'ordering': ['week__week_no'],
                'indexes': [models.Index(fields=['is_active'], name='visits_week_is_acti_6c4de8_idx')],
                'constraints': [models.UniqueConstraint(fields=('week',), name='uniq_weekly_letterlink_week')],
            },
        ),
    ]
