# Generated by Django 6.0.1 on 2026-03-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_weeklyletterlink'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklyletterlink',
            name='uniq_weekly_letterlink_week',
        ),
    ]
