# Generated by Django 6.0.1 on 2026-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0008_remove_weeklyletterlink_uniq_weekly_letterlink_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='planday',
            name='visit_note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ملاحظة تنفيذ الزيارة'),
        ),
        migrations.AddField(
            model_name='planday',
            name='visited',
            field=models.BooleanField(default=False, verbose_name='تمت الزيارة'),
        ),
        migrations.AddField(
            model_name='planday',
            name='visited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تنفيذ الزيارة'),
        ),
        migrations.AlterField(
            model_name='supervisornotification',
            name='notif_type',
            field=models.CharField(choices=[('approved', 'تم اعتماد الخطة'), ('returned', 'تمت إعادة الخطة للمراجعة'), ('unlock_approved', 'تم قبول طلب فك الاعتماد'), ('unlock_rejected', 'تم رفض طلب فك الاعتماد'), ('admin_alert', 'تنبيه إداري')], max_length=30, verbose_name='نوع الإشعار'),
        ),
        migrations.AddIndex(
            model_name='planday',
            index=models.Index(fields=['visited'], name='visits_plan_visited_c0aa35_idx'),
        ),
    ]
