# Generated by Django 6.0.1 on 2026-03-22 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0009_planday_visit_note_planday_visited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم القطاع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قطاع',
                'verbose_name_plural': 'القطاعات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإسناد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='gender',
            field=models.CharField(blank=True, choices=[('boys', 'بنين'), ('girls', 'بنات')], max_length=10, null=True, verbose_name='النوع'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['is_active'], name='visits_assi_is_acti_b2ca23_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_at'], name='visits_assi_created_690d56_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['name'], name='visits_sect_name_7d5636_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['is_active'], name='visits_sect_is_acti_3406d4_idx'),
        ),
        migrations.AddField(
            model_name='school',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='visits.sector', verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='visits.sector', verbose_name='القطاع'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['gender'], name='visits_scho_gender_b8fca5_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['sector'], name='visits_scho_sector__90752b_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['gender'], name='visits_supe_gender_4f1401_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['sector'], name='visits_supe_sector__7f044a_idx'),
        ),
    ]
