# Generated by Django 6.0.1 on 2026-03-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_sector_assignment_created_at_assignment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='بوابة الزيارات', max_length=150, verbose_name='اسم الموقع')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة مفعّل')),
                ('maintenance_message', models.TextField(blank=True, default='الموقع مغلق مؤقتًا للصيانة، وسيعود العمل خلال وقت قريب.', null=True, verbose_name='رسالة الصيانة')),
                ('allow_admin_only', models.BooleanField(default=True, help_text='عند التفعيل: يمكن للإدارة فقط الدخول أثناء وضع الصيانة.', verbose_name='السماح للإدارة فقط أثناء الصيانة')),
                ('expected_return_text', models.CharField(blank=True, help_text='مثال: اليوم الساعة 3 مساءً أو خلال ساعة تقريبًا', max_length=200, null=True, verbose_name='وقت العودة المتوقع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
