# Generated by Django 6.0.1 on 2026-03-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_ends_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت انتهاء الصيانة وإعادة فتح الموقع.', null=True, verbose_name='نهاية الصيانة'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_starts_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت بدء الصيانة.', null=True, verbose_name='بداية الصيانة'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='expected_return_text',
            field=models.CharField(blank=True, help_text='مثال: اليوم الساعة 3 مساءً أو خلال ساعة تقريبًا', max_length=200, null=True, verbose_name='وقت العودة المتوقع (نصي)'),
        ),
    ]
