# Generated by Django 6.0.1 on 2026-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_sitesetting_maintenance_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل التنبيهات البريدية'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق من البريد'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['email_notifications_enabled'], name='visits_supe_email_n_5f0b8f_idx'),
        ),
    ]
