# Generated by Django 6.0.1 on 2026-03-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_supervisor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('code', models.CharField(max_length=6, verbose_name='رمز التحقق')),
                ('purpose', models.CharField(choices=[('email_verification', 'التحقق من البريد'), ('login', 'تسجيل الدخول'), ('password_reset', 'إعادة تعيين كلمة المرور')], default='email_verification', max_length=50, verbose_name='الغرض')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي في')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التحقق')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to='visits.supervisor', verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'رمز تحقق البريد',
                'verbose_name_plural': 'رموز تحقق البريد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose'], name='visits_emai_email_143857_idx'), models.Index(fields=['is_used'], name='visits_emai_is_used_c89a92_idx'), models.Index(fields=['expires_at'], name='visits_emai_expires_14067e_idx')],
            },
        ),
    ]
