# Generated by Django 6.0.1 on 2026-05-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0014_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(db_index=True, help_text='يمنع تكرار نفس الحالة الرقابية للمشرف والأسبوع والخطة.', max_length=220, unique=True, verbose_name='المفتاح الفريد للحالة')),
                ('issue_type', models.CharField(choices=[('incomplete_plan', 'خطة غير مكتملة'), ('not_saved_plan', 'لم يحفظ خطة الأسبوع'), ('unlock_request', 'طلب فك اعتماد'), ('uncovered_schools', 'مدارس غير مغطاة')], db_index=True, max_length=40, verbose_name='نوع الحالة')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('notified', 'تم التنبيه'), ('pending_admin', 'بانتظار مراجعة الإدارة'), ('processed', 'تمت المعالجة'), ('closed', 'مغلقة إداريًا')], db_index=True, default='open', max_length=30, verbose_name='حالة المتابعة')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان الحالة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الحالة')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='ملاحظة/تنبيه الإدارة')),
                ('supervisor_response', models.TextField(blank=True, null=True, verbose_name='إفادة المشرف')),
                ('supervisor_response_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إفادة المشرف')),
                ('admin_review_note', models.TextField(blank=True, null=True, verbose_name='ملاحظة مراجعة الإدارة')),
                ('notification_count', models.PositiveIntegerField(default=0, verbose_name='عدد التنبيهات')),
                ('last_notification_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تنبيه')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرصد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_control_followups', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_followups', to='visits.plan', verbose_name='الخطة المرتبطة')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_followups', to='visits.supervisor', verbose_name='المشرف')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_followups', to='visits.planweek', verbose_name='الأسبوع')),
            ],
            options={
                'verbose_name': 'متابعة رقابية',
                'verbose_name_plural': 'سجل المتابعة الرقابية',
                'ordering': ['-updated_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['unique_key'], name='visits_cont_unique__eaa35a_idx'), models.Index(fields=['issue_type'], name='visits_cont_issue_t_65bd56_idx'), models.Index(fields=['status'], name='visits_cont_status_25282d_idx'), models.Index(fields=['status', 'issue_type'], name='visits_cont_status_83db8d_idx'), models.Index(fields=['supervisor', 'status'], name='visits_cont_supervi_408e36_idx'), models.Index(fields=['week', 'issue_type'], name='visits_cont_week_id_a149ae_idx'), models.Index(fields=['last_notification_at'], name='visits_cont_last_no_f3e573_idx'), models.Index(fields=['created_at'], name='visits_cont_created_29b062_idx')],
            },
        ),
    ]
