# Generated by Django 6.0.1 on 2026-05-04 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0015_controlfollowup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت فك الاعتماد'),
        ),
        migrations.AddField(
            model_name='plan',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_visit_plans', to=settings.AUTH_USER_MODEL, verbose_name='فُك الاعتماد بواسطة'),
        ),
        migrations.AddField(
            model_name='plan',
            name='unlocked_reason',
            field=models.TextField(blank=True, help_text='يحفظ سبب المشرف وملاحظة الإدارة عند قبول فك الاعتماد.', null=True, verbose_name='سبب فك الاعتماد'),
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة الإدارة على طلب الفك'),
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='previous_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='حالة الخطة قبل الطلب'),
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب طلب فك الاعتماد'),
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unlock_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمدة'), ('unlock', 'طلب فك اعتماد'), ('unlocked', 'مفكوكة للتعديل')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='ControlFollowUpAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('detected', 'رصد الحالة'), ('updated_detection', 'تحديث الرصد'), ('notified', 'إرسال تنبيه'), ('supervisor_response', 'إفادة المشرف'), ('accepted', 'قبول المعالجة'), ('returned', 'إعادة للمشرف'), ('closed', 'إغلاق إداري'), ('unlock_requested', 'طلب فك اعتماد'), ('unlock_approved', 'قبول فك الاعتماد'), ('unlock_rejected', 'رفض فك الاعتماد'), ('plan_reapproved', 'إعادة اعتماد بعد الفك')], max_length=40, verbose_name='نوع الإجراء')),
                ('from_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='الحالة السابقة')),
                ('to_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='الحالة الجديدة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة الإجراء')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('actor_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_followup_actions', to='visits.supervisor', verbose_name='المشرف المنفذ')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_followup_actions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنفذ')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='visits.controlfollowup', verbose_name='حالة المتابعة')),
            ],
            options={
                'verbose_name': 'إجراء متابعة رقابية',
                'verbose_name_plural': 'إجراءات المتابعة الرقابية',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action_type'], name='visits_cont_action__928879_idx'), models.Index(fields=['created_at'], name='visits_cont_created_09a324_idx')],
            },
        ),
    ]
