# Generated by Django 6.0.1 on 2026-05-18 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0016_plan_unlocked_at_plan_unlocked_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principal',
            options={'ordering': ['school__name', 'full_name'], 'verbose_name': 'قائد مدرسة', 'verbose_name_plural': 'قادة المدارس'},
        ),
        migrations.AddField(
            model_name='principal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='principal',
            name='current_work',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='العمل الحالي'),
        ),
        migrations.AddField(
            model_name='principal',
            name='faris_status',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='حالة فارس'),
        ),
        migrations.AddField(
            model_name='principal',
            name='gender',
            field=models.CharField(blank=True, choices=[('boys', 'بنين'), ('girls', 'بنات')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='principal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='principal',
            name='last_imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر استيراد'),
        ),
        migrations.AddField(
            model_name='principal',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, help_text='يحفظ داخليًا للمطابقة والتحقق، ولا يُعرض في بوابة الاطلاع.', max_length=20, null=True, verbose_name='السجل المدني'),
        ),
        migrations.AddField(
            model_name='principal',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة'),
        ),
        migrations.AddField(
            model_name='principal',
            name='qualification',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='المؤهل'),
        ),
        migrations.AddField(
            model_name='principal',
            name='rank',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='الرتبة'),
        ),
        migrations.AddField(
            model_name='principal',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم ملف الاستيراد'),
        ),
        migrations.AddField(
            model_name='principal',
            name='specialization',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='principal',
            name='stage',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='المرحلة'),
        ),
        migrations.AddField(
            model_name='principal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='اسم القائد/ة'),
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['national_id'], name='visits_prin_nationa_7f7864_idx'),
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['gender'], name='visits_prin_gender_f8e68a_idx'),
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['stage'], name='visits_prin_stage_96684e_idx'),
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['faris_status'], name='visits_prin_faris_s_4493e2_idx'),
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['current_work'], name='visits_prin_current_83ba1d_idx'),
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['is_active'], name='visits_prin_is_acti_53a308_idx'),
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['last_imported_at'], name='visits_prin_last_im_bdf73b_idx'),
        ),
    ]
