# Generated by Django 6.0.1 on 2026-05-21 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0017_alter_principal_options_principal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planweek',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='الأسبوع الحالي للمشرفين'),
        ),
        migrations.AddField(
            model_name='planweek',
            name='is_open_for_supervisors',
            field=models.BooleanField(default=False, verbose_name='مفتوح للمشرفين'),
        ),
        migrations.AddField(
            model_name='planweek',
            name='semester_week_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='رقم الأسبوع داخل الفصل'),
        ),
        migrations.AlterField(
            model_name='planday',
            name='no_visit_reason',
            field=models.CharField(blank=True, choices=[('meeting', 'اجتماع'), ('training', 'تدريب'), ('event', 'لقاء/فعالية'), ('office', 'عمل مكتبي'), ('official_holiday', 'إجازة رسمية / يوم مغلق'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='سبب عدم الزيارة'),
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='العام الدراسي')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العام')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العام')),
                ('is_current', models.BooleanField(default=False, verbose_name='العام الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'عام دراسي',
                'verbose_name_plural': 'الأعوام الدراسية',
                'ordering': ['-starts_at', '-id'],
                'indexes': [models.Index(fields=['is_current'], name='visits_acad_is_curr_8564e1_idx'), models.Index(fields=['is_active'], name='visits_acad_is_acti_4ddf98_idx')],
            },
        ),
        migrations.AddField(
            model_name='planweek',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeks', to='visits.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.CreateModel(
            name='PlanClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'الأحد'), (1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('reason_type', models.CharField(choices=[('national_day', 'اليوم الوطني'), ('foundation_day', 'يوم التأسيس'), ('official_holiday', 'إجازة رسمية'), ('study_suspended', 'تعليق دراسة'), ('other', 'أخرى')], default='official_holiday', max_length=30, verbose_name='نوع الإغلاق')),
                ('reason_title', models.CharField(default='إجازة رسمية', max_length=150, verbose_name='سبب الإغلاق')),
                ('count_as_completed', models.BooleanField(default=True, verbose_name='يُحسب مكتملًا')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_days', to='visits.planweek', verbose_name='الأسبوع')),
            ],
            options={
                'verbose_name': 'يوم مغلق في الخطة',
                'verbose_name_plural': 'الأيام المغلقة في الخطط',
                'ordering': ['week__week_no', 'weekday'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'الفصل الدراسي الأول'), (2, 'الفصل الدراسي الثاني')], verbose_name='الفصل الدراسي')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='اسم الفصل')),
                ('starts_at', models.DateField(verbose_name='تاريخ بداية الفصل')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الفصل')),
                ('weeks_count', models.PositiveSmallIntegerField(default=19, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='عدد الأسابيع')),
                ('is_current', models.BooleanField(default=False, verbose_name='الفصل الحالي')),
                ('is_open', models.BooleanField(default=False, verbose_name='مفتوح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='visits.academicyear', verbose_name='العام الدراسي')),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'ordering': ['academic_year__starts_at', 'number'],
            },
        ),
        migrations.AddField(
            model_name='planweek',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeks', to='visits.semester', verbose_name='الفصل الدراسي'),
        ),
        migrations.AddIndex(
            model_name='planweek',
            index=models.Index(fields=['is_current'], name='visits_plan_is_curr_bdce2b_idx'),
        ),
        migrations.AddIndex(
            model_name='planweek',
            index=models.Index(fields=['is_open_for_supervisors'], name='visits_plan_is_open_ddddd8_idx'),
        ),
        migrations.AddIndex(
            model_name='planweek',
            index=models.Index(fields=['semester', 'semester_week_no'], name='visits_plan_semeste_76d5be_idx'),
        ),
        migrations.AddIndex(
            model_name='planclosedday',
            index=models.Index(fields=['weekday'], name='visits_plan_weekday_9762fb_idx'),
        ),
        migrations.AddIndex(
            model_name='planclosedday',
            index=models.Index(fields=['reason_type'], name='visits_plan_reason__c87a80_idx'),
        ),
        migrations.AddIndex(
            model_name='planclosedday',
            index=models.Index(fields=['is_active'], name='visits_plan_is_acti_90994b_idx'),
        ),
        migrations.AddConstraint(
            model_name='planclosedday',
            constraint=models.UniqueConstraint(fields=('week', 'weekday'), name='uniq_plan_closed_day_week_weekday'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['number'], name='visits_seme_number_5d4686_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_current'], name='visits_seme_is_curr_c4ca64_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_open'], name='visits_seme_is_open_a8fcce_idx'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('academic_year', 'number'), name='uniq_semester_academic_year_number'),
        ),
    ]
