# Generated by Django 6.0.1 on 2026-05-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0018_planweek_is_current_planweek_is_open_for_supervisors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('plan_approved', 'اعتماد الخطة'), ('plan_returned', 'إرجاع الخطة للتعديل'), ('unlock_requested', 'طلب فك اعتماد'), ('unlock_approved', 'قبول فك الاعتماد'), ('unlock_rejected', 'رفض فك الاعتماد'), ('admin_alert', 'تنبيه إداري'), ('control_followup', 'ملاحظة رقابية'), ('incomplete_reminder', 'تذكير بعدم اكتمال الخطة'), ('weekly_summary', 'ملخص أسبوعي')], max_length=40, verbose_name='نوع الرسالة')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد المرسل إليه')),
                ('subject', models.CharField(max_length=250, verbose_name='عنوان الرسالة')),
                ('body_preview', models.TextField(blank=True, null=True, verbose_name='مختصر الرسالة')),
                ('status', models.CharField(choices=[('sent', 'أُرسلت'), ('skipped', 'لم تُرسل'), ('failed', 'فشل الإرسال')], default='skipped', max_length=20, verbose_name='حالة الإرسال')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='visits.plan', verbose_name='الخطة')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='visits.supervisor', verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'سجل بريد إلكتروني',
                'verbose_name_plural': 'سجل البريد الإلكتروني',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['supervisor', 'event_type'], name='visits_emai_supervi_518e5f_idx'), models.Index(fields=['status'], name='visits_emai_status_fd80f8_idx'), models.Index(fields=['created_at'], name='visits_emai_created_43546c_idx'), models.Index(fields=['sent_at'], name='visits_emai_sent_at_433c47_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_approved', models.BooleanField(default=True, verbose_name='تنبيه اعتماد الخطة')),
                ('plan_returned', models.BooleanField(default=True, verbose_name='تنبيه إرجاع الخطة للتعديل')),
                ('unlock_result', models.BooleanField(default=True, verbose_name='تنبيه نتيجة طلب فك الاعتماد')),
                ('admin_alert', models.BooleanField(default=True, verbose_name='التنبيهات الإدارية')),
                ('control_followup', models.BooleanField(default=True, verbose_name='الملاحظات الرقابية')),
                ('incomplete_reminder', models.BooleanField(default=True, verbose_name='تذكير عدم اكتمال الخطة')),
                ('weekly_summary', models.BooleanField(default=False, verbose_name='ملخص أسبوعي')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to='visits.supervisor', verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'تفضيلات التنبيهات البريدية',
                'verbose_name_plural': 'تفضيلات التنبيهات البريدية',
                'indexes': [models.Index(fields=['supervisor'], name='visits_emai_supervi_df241f_idx')],
            },
        ),
    ]
